# general settings
# 001_MSRResNet_x4_f64b16_DIV2K_1000k_B16G1_wandb
# name: 029_MSVR_600K_Pcd8TSAReconsUp_Charbonnier_F7Feat16Res20BN2
# name: 037_MSVR_600K_Pcd8TSAReconsMeta_Charbonnier_F7Feat16MetaFeatRes20BN2
# name: 039_MSVR_600K_Pcd8noPTSAReconsMeta_Charbonnier_F7Feat16MetaRes20BN2_DEBUG
# name: 1.001_MSVR_600K_cd8TSAnpReconsMeta_Charbonnier_F7Feat16MetaRes20BN4
# name: 1.004_MSVR_600K_cd8TNAReconsMeta_l1_F7Feat16MetaRes20BN4_3.8S
# name: 1.004_MSVR_600K_cd8TNARSAMeta_l1_F7Feat16MetaRes20BN4
# name: 1.004_MSVR_600K_cd8TNARSAMeta_l1_F7Feat16MetaRes20BN4_continue
# name: onlyMeta_test_prii
# name: base_debug
# name: 1.005_prii_xs_addconv
# name: 1.005_prii_xs_vpp
name: 1.006_sarm_xs_vpp
# name: 1.007_base_xs_vpp
# name: 1.009_edvrc_xs
# name: 1.008_asvsr_xs_vpp_selected
# name: 1.008_asvsr_xs_vpp
# name: 1.003_MSVR_600K_cd8TSAnpReconsUWLB_l1_F7Feat16MetaRes20BN4
# name: EDVR-change-XS-lr
# name: 038_MSVR_600K_Pcd8TSAReconsUWLB_Charbonnier_F7Feat128MetaRes40BN2_DEBUG
# name: 036_MSVR_600K_Pcd8TSAReconsMeta_Charbonnier_F7Feat16MetaRes20BN2_random
# name: 034_MSVR_600K_Pcd8TSAReconsVPosMeta_Charbonnier_F7Feat16Res20BN2
# name: 035_MSVR_600K_Pcd8TSAReconsMeta_Charbonnier_F7Feat16Res20BN2_3.5-4.0
# name: 031_MSVR_600K_Pcd8TSAScaleReconsMeta_Charbonnier_F7Feat64BN2
# name: 027_MSVR_600K_Pcd8TSAReconsMeta_Charbonnier_F7Feat64BN2_3.4S
# name: 028_MSVR_600K_Pcd8TSAReconsMulFeatMeta_Charbonnier_F7Feat16Res20BN2
# name: MSVR_Vimeo90K_600k_valVimeo90K_Pcd4FuseMeta_L1_F7G064Feat64
model_type: MSVRModel
scale: [2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3.0,3.1,3.2,3.3,3.4,3.5,3.6,3.7,3.8,3.9,4.0]
# scale: [2.0,2.3,2.5,2.6,2.8,3.0,3.3,3.5,3.6,3.8,4.0]
# scale: [4.0]
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
accumulation_steps: 2
fix_hr: true
print_net_g: true
log_scale: true
pbar: true

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: msmtVimeo90KDataset
    dataroot_gt: /home/hdr/disks/D/Datasets/vimeo_septuplet/sequences
    dataroot_lq: /home/hdr/disks/D/Datasets/vimeo_septuplet_matlab_X1_X4
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    # meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_test_GT_00001.txt
    # meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT_00001.txt
    # val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    num_frame: 7
    lq_size: 64
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true
    use_edge: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 200
    prefetch_mode: muti-scale
    pin_memory: true
  # train:
  #   name: Vimeo90K
  #   type: Vimeo90KDatasetOTF
  #   dataroot_gt: /mnt/hard_disk/gaihe/datasets/vimeo_septuplet/sequences
  #   dataroot_lq: /mnt/hard_disk/gaihe/datasets/vimeo_septuplet/sequences
  #   dataroot_flow: ~
  #   meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_test_GT_00001.txt
  #   # val_partition: REDS4  # set to 'official' when use the official validation partition
  #   io_backend:
  #     type: disk

  #   num_frame: 7
  #   lq_size: 256
  #   interval_list: [1]
  #   random_reverse: false
  #   use_flip: true
  #   use_rot: true
  #   use_edge: false

  #   # data loader
  #   use_shuffle: true
  #   num_worker_per_gpu: 3
  #   batch_size_per_gpu: 1
  #   dataset_enlarge_ratio: 200
  #   prefetch_mode: muti-scale
  #   pin_memory: true
  #   OTFMode: PIL

  val:
    name: msVid4
    type: msmtVid4
    dataroot_gt: datasets/Vid4/gt
    dataroot_lq: /home/hdr/disks/D/Datasets/vid4_matlabX1_X4
    io_backend:
      type: disk

    cache_data: false
    num_frame: 7
    padding: reflection_circle
    fixed_scale: 4.0

    # name: Vimeo90K-Test
    # type: msVimeo90KDatasetTest
    # dataroot_gt: /mnt/hard_disk/gaihe/datasets/vimeo_septuplet/sequences
    # dataroot_lq: /mnt/hard_disk/gaihe/datasets/vimeo_septuplet_matlab_X1_X4
    # # meta_info_file: basicsr/data/meta_info/meta_info_Vimeo10K_test_GT.txt
    # meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_test_GT_00001.txt
    # # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    # io_backend:
    #   type: disk
    
    # num_frame: 7
    # padding: reflection_circle

    # cache_data: false
    # random_reverse: false
    # use_flip: false
    # use_rot: false
    # use_edge: false
    
    # use_shuffle: false
    # num_worker_per_gpu: 1
    # batch_size_per_gpu: 1
    # prefetch_mode: muti-scale
    # pin_memory: true
    # fixed_scale: 4.0
    # OTFMode: PIL

# network structures
network_g:
  type: MSVR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 16
  kSize: 3
  num_edge_feat: 64
  num_frame: 7
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 40
  center_frame_idx: ~
  vis_feature: false
  hr_in: false
  is_bicubic: false
  pix_attn: false
  with_basicvsrpp: true
  with_pcd: false
  with_cd: false
  with_recons: false
  with_scaleAware: true
  with_scalefilter: false
  with_tsa: false
  with_tsanp: false
  with_meta: true
  with_uwlb: false
  uwlb_args:
    with_offset: true
    with_feature: true
    with_gradBack: true
    with_f2f: false
    scale: [2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3.0,3.1,3.2,3.3,3.4,3.5,3.6,3.7,3.8,3.9,4.0]
    # scale: [2.0,2.3,2.5,2.6,2.8,3.0,3.3,3.5,3.6,3.8,4.0]
    # scale: [3.8]
  vpp_args:
    num_blocks: 7
    spynet_pretrained: 'experiments/pretrained_models/spynet/spynet_20210409-c6c1bd09.pth'
    scale: [2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3.0,3.1,3.2,3.3,3.4,3.5,3.6,3.7,3.8,3.9,4.0]
    # scale: [2.0,2.3,2.5,2.6,2.8,3.0,3.3,3.5,3.6,3.8,4.0]
    is_component: true
    # scale: [4.0]
  with_edge: false
  with_lr: false
  with_videoPosMatrix: false
  with_resNfMeta: false
  with_resMeta: true
  with_onlyMeta: false
  with_resFeat: false
  meta_args:
    # num_feat: 64
    num_block: 16
    nConv: 8
    n_colors: 3
    scale: [2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3.0,3.1,3.2,3.3,3.4,3.5,3.6,3.7,3.8,3.9,4.0]
    # scale: [2.0,2.3,2.5,2.6,2.8,3.0,3.3,3.5,3.6,3.8,4.0]
    # scale: [3.5,3.6,3.7,3.8,3.9,4.0]
    # scale: [3.8]
    # res_scale: 0.1
    img_range: 1.
    rgb_mean: [0.4488, 0.4371, 0.4040]
    rgb_std: [1.0, 1.0, 1.0]
    ConstantWeightUpsample: false

# path
path:
  # pretrain_network_g: experiments/onlyMeta_test_prii_7f/models/net_g_180000.pth
  strict_load_g: true
  # resume_state: experiments/1.009_edvrc_xs/training_states/120000.state
  # resume_state: /mnt/hard_disk/gaihe/code/BasicSR-master/experiments/EDVR-change-XS/training_states/480000.state
  # resume_state: /mnt/hard_disk/gaihe/code/BasicSR-master/experiments/038_MSVR_600K_Pcd8TSAReconsUWLB_Charbonnier_F7Feat16MetaRes20BN2/training_states/180000.state
  # resume_state: /mnt/hard_disk/gaihe/code/BasicSR-master/experiments/1.002_MSVR_600K_cd8TSAnpReconsUWLBgrad_l1_F7Feat16MetaRes20BN4/training_states/260000.state
  # resume_state: /home/gaihe/gaihe/BasicSR-master/experiments/036_MSVR_600K_Pcd8TSAReconsMeta_Charbonnier_F7Feat16MetaRes20BN2/training_states/1200000.state
  # resume_state: experiments/1.007_base_xs_vpp_selected/training_states/15000.state
  # resume_state: experiments/1.007_base_xs_vpp/training_states/440000.state
  # resume_state: experiments/1.006_sarm_xs/training_states/450000.state
  # resume_state: experiments/1.006_sarm_xs_vpp_if/training_states/390000.state
  # resume_state: experiments/1.007_base_xs_vpp_selected/training_states/86919.state
  # resume_state: experiments/1.005_prii_xs_vpp/training_states/485502.state
  # resume_state: experiments/1.008_asvsr_xs_vpp/training_states/136431.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    # lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  # scheduler:
  #   type: CosineAnnealingRestartLR
  #   # periods: [100000, 200000, 300000, 300000, 300000, 600000, 600000]
  #   periods: [400000, 800000, 1200000, 1200000, 1200000, 2400000, 2400000]
  #   restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  #   eta_min: !!float 1e-7
  scheduler:
    type: CosineAnnealingRestartLR
    # periods: [100000, 200000, 300000, 300000, 300000, 600000, 600000]
    periods: [600000, 600000]
    restart_weights: [1, 0.5]
    eta_min: !!float 1e-7
  # scheduler:
  #   type: MultiStepRestartLR
  #   milestones: [600000, 600000, 600000, 600000]
  #   gamma: 0.5
  #   restart_weights: [1]
    # eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  dcn_lr_mul: 1
  spy_lr_mul: 0.25
  tsa_iter: 1
  # refresh_sechduler: true

  # losses
  pixel_opt:
    # type: L1Loss
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      scale: 2.0
      crop_border: 0
      test_y_channel: false
    # psnr: # metric name, can be arbitrary
      # type: calculate_psnr
      # crop_border: 0
      # test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
