# general settings
name: dist_test
model_type: DistTestModel
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 10
fix_hr: true
print_net_g: true
pbar: true
scale: [2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3.0,3.1,3.2,3.3,3.4,3.5,3.6,3.7,3.8,3.9,4.0]

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: msVimeo90KDataset
    dataroot_gt: /home/hdr/disks/D/Datasets/vimeo_septuplet/sequences
    dataroot_lq: /home/hdr/disks/D/Datasets/vimeo_septuplet_matlab_X1_X4
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    io_backend:
      type: disk

    num_frame: 7
    lq_size: 64
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true
    use_edge: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 200
    prefetch_mode: cuda
    pin_memory: true

# network structures
network_g:
  type: distNet

# path
path:
  strict_load_g: true

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    # lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000, 600000]
    restart_weights: [1, 0.5]
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1  # no warm up
  dcn_lr_mul: 1
  spy_lr_mul: 0.25
  tsa_iter: 1
  # refresh_sechduler: true

  # losses
  pixel_opt:
    # type: L1Loss
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      scale: 2.0
      crop_border: 0
      test_y_channel: false
    # psnr: # metric name, can be arbitrary
      # type: calculate_psnr
      # crop_border: 0
      # test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
