# general settings
# name: 002_ParabolicBRDF_HOMO_600k_B32_DEBUG # initialization
# name: 003_Dense3D_HOMO_600k_B32_DEBUG # noise
name: 004_Dense3D_HOMO_600k_B32 # no grad

model_type: IRFModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: parabolicDataset
    type: parabolicDataset
    brdf_args:
      split_num: 5
      nbRendering: 1
      split_axis: 1
      concat: True
      svbrdf_norm: True
      size: 64
      order: 'pndrs'
      permute_channel: True
      toLDR: true
      useArg: false
      lampIntensity: 0.1
      dis: 1
    mirror_args:
      f: 5.08
      dia: 5.08
      y_offset: 10.16
      xy_reso: 
        x: 256
        y: 256
      rotation_mode: 'xyz'
      eular: [0, 0, 0]
      T: [0, 0, 0]
      o: [1,10.16,10]
      d: [0,0,-1]
      fixed_light: True
    data_root: /home/sda/Dense3D
    jitter: false
    range_d: [0,1]
    range_s: [0,1]
    range_r: [0.1,0.8]
    len: 5120000
    spec_n: 20
    mode: folder
    use_grad: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true
    io_backend:
      type: disk

  val:
    name: parabolicDataset
    type: parabolicDataset
    brdf_args:
      split_num: 5
      nbRendering: 1
      split_axis: 1
      concat: True
      svbrdf_norm: True
      size: 64
      order: 'pndrs'
      permute_channel: True
      toLDR: true
      useArg: false
      lampIntensity: 0.1
      dis: 1
    mirror_args:
      f: 5.08
      dia: 5.08
      y_offset: 10.16
      xy_reso: 
        x: 256
        y: 256
      rotation_mode: 'xyz'
      eular: [0, 0, 0]
      T: [0, 0, 0]
      o: [1,10.16,10]
      d: [0,0,-1]
      fixed_light: True
    data_root: /home/sda/Dense3D
    jitter: false
    range_d: [0,1]
    range_s: [0,1]
    range_r: [0.1,0.8]
    len: 100
    spec_n: 20
    mode: generate
    use_grad: False
    io_backend:
      type: disk

# network structures
network_g:
  type: Dense3D
  brdf_args:
    split_num: 5
    nbRendering: 1
    split_axis: 1
    concat: True
    svbrdf_norm: True
    size: 1024
    order: 'pndrs'
    toLDR: True
  in_channel: 3
  out_channel: 7
  oh: 256
  ow: 256
  init_method: 'xavier'
  channel_num: 16

# path
path:
  # pretrain_network_g: ~
  strict_load_g: true
  # resume_state: experiments/003_Dense3D_HOMO_600k_B32/training_states/61271.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [20000, 50000, 50000, 130000, 350000]
    restart_weights: [1, 0.5, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7
  # scheduler:
  #   type: CosineAnnealingRestartLR
  #   periods: [10000, 10000, 30000, 100000, 150000, 300000]
  #   restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.2]
  #   eta_min: !!float 1e-7
  # scheduler:
  #   type: MultiStepRestartLR
  #   milestones: [100000, 200000, 300000]
    # milestones: [1,5,10,15]

  total_iter: 600000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  # losses
  # cos_opt:
  #   type: CosineLoss
  #   loss_weight: 0.5
  #   reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: true
  save_num: 10

  metrics:
    # cosine: # metric name, can be arbitrary
    #   type: cos
    #   weight: 2
    pixel: # metric name, can be arbitrary
      type: pix
      weight: 1

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true