# general settings
name: NAFNetHFRenderLoss_allbands_render40w  # initialization

model_type: nafnet
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: areaDataset
    type: areaDataset
    brdf_args:
      nbRendering: 1
      size: 256
      order: pndrs
      toLDR: True
      lampIntensity: 12
    data_path: /home/sda/svBRDFs/trainBlended # Ruby
    # data_path: /home/xh/cjm/18single_image/Data_Deschaintre18/trainBlended # 2080Ti
    # rendering_path: /home/sda/svBRDFs/
    light_mode: point
    input_mode: render
    log: False
    gamma: True
    io_backend: 
      type: disk
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: areaDataset
    type: areaDataset
    brdf_args:
      nbRendering: 1
      size: 256
      order: pndrs
      toLDR: True
      lampIntensity: 12
    data_path: /home/sda/svBRDFs/testBlended # Ruby
    # data_path: /home/xh/cjm/18single_image/Data_Deschaintre18/trainBlended # 2080Ti
    # data_path: /home/xh/cjm/18single_image/Data_Deschaintre18/testBlended # 2080Ti
    # rendering_path: /home/sda/svBRDFs/
    log: False
    gamma: True
    light_mode: point
    input_mode: render
    io_backend: 
      type: disk
    len: 18

# network structures
network_g:
  type: NAFNetHF
  width: 32
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]
  brdf_args:
    nbRendering: 1
    size: 256
    order: pndrs
    toLDR: True
    lampIntensity: 12
    # lampIntensity: 12

# network_d:
#   type: PatchDiscriminator
# path
path:
  # pretrain_network_g: ~
  strict_load_g: true
  # resume_state: experiments/NAFNetL1Loss_pickbands_spe/training_states/200000.state

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]
  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7
    # milestones: [1,5,10,15]
  # total_iter: 300000
  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  # highfrequency_opt:
  #   type: L1Loss
  #   loss_weight: 0.01
  #   reduction: mean
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  render_opt:
    type: L1LogLoss
    loss_weight: 0.1
    reduction: mean
    eps: 0.01
  #loss index
  noramalpixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  diffusepixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  roughnesspixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  specularpixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
# validation settings
val:
  # val_freq: !!float 1e0
  val_freq: !!float 2e4
  save_img: true

  metrics:
    # cosine: # metric name, can be arbitrary
    #   type: cos
    #   weight: 2
    pixel: # metric name, can be arbitrary
      type: pix
      weight: 1
    highfrequency: # metric name, can be arbitrary
      type: HF
      weight: 1
    normal_highfrequency: # metric name, can be arbitrary
      type: normal_pix
      weight: 1
    diffuse_highfrequency: # metric name, can be arbitrary
      type: diffuse_pix
      weight: 1
    roughness_highfrequency: # metric name, can be arbitrary
      type: roughness_pix
      weight: 1
    specular_highfrequency: # metric name, can be arbitrary
      type: specular_pix
      weight: 1
    lowfrequency: # metric name, can be arbitrary
      type: LF
      weight: 1
    SSIM:
      type: ssim
      weight: 1

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true