# general settings
# name: 001_IRF_HOMO_600k_B32 # basic max pooling, shadow, fix intensity
# name: 002_IRF_HOMO_600k_B128 # random intensity, no shadow
# name: 003_IRF_HOMO_600k_B128 # jitter, random normal
# name: 004_IRF_HOMO_600k_B128 # attn
# name: 005_IRF_HOMO_600k_B128 # lrelu attn
# name: 006_IRF_HOMO_600k_B128 # random light/view
name: 007_IRF_HOMO_600k_B128_DEBUG # rated plane normal, midcode

model_type: IRFModel
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: homoDataset
    type: homoDataset
    brdf_args:
      split_num: 5
      nbRendering: 1
      split_axis: 1
      concat: True
      svbrdf_norm: True
      size: 64
      order: 'pndrs'
      permute_channel: True
      toLDR: True
    jitter: false
    len: 51200000
    range_d: [0,1]
    range_s: [0,1]
    range_r: [0.1,0.8]
    range_n: {"theta":[0,89],"phi":[0,360]}
    nb: 2500
    rand_nb: false
    rand_lv: true
    mix_plane: True
    plane_rate: 0.3

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 128
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: homoDataset
    type: homoDataset
    brdf_args:
      split_num: 5
      nbRendering: 1
      split_axis: 1
      concat: True
      svbrdf_norm: True
      size: 256
      order: 'pndrs'
      permute_channel: True
      toLDR: True

    len: 100
    range_d: [0,1]
    range_s: [0,1]
    range_r: [0,1]
    range_n: {"theta":[0,89],"phi":[0,360]}
    nb: 10

# network structures
network_g:
  type: IRF
  brdf_args:
    split_num: 5
    nbRendering: 1
    split_axis: 1
    concat: True
    svbrdf_norm: True
    size: 1024
    order: 'pndrs'
    toLDR: True
  num_in_ch: 15
  num_out_ch: 7
  attn_fusion: False
  encode_layer: [
    [256,512],
    [512,512]
  ]
  midcode_layer: [
    [1024,512],
    [512,512]
  ]
  decode_layer: [
    [512,512],
    [512,256]
  ]
  attn_layer: [
    [512,512],
    [512,512]
  ]

# path
path:
  # pretrain_network_g: ~
  strict_load_g: true
  # resume_state: experiments/006_IRF_HOMO_600k_B128/models/net_g_latest.pth

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  # scheduler:
  #   type: CosineAnnealingRestartLR
  #   periods: [20000, 30000, 100000, 200000, 300000]
  #   restart_weights: [1, 0.5, 0.5, 0.5, 0.5]
  #   eta_min: !!float 1e-7
  # scheduler:
  #   type: CosineAnnealingRestartLR
  #   periods: [10000, 10000, 30000, 100000, 150000, 300000]
  #   restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.2]
  #   eta_min: !!float 1e-7
  scheduler:
    type: MultiStepRestartLR
    milestones: [300000, 500000]
    # milestones: [1,5,10,15]

  total_iter: 600000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  # losses
  # cos_opt:
  #   type: CosineLoss
  #   loss_weight: 0.5
  #   reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: true
  save_num: 10

  metrics:
    # cosine: # metric name, can be arbitrary
    #   type: cos
    #   weight: 2
    pixel: # metric name, can be arbitrary
      type: pix
      weight: 1

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true