# general settings
name: Baseline_EDVR_S_x4_SR_MSVRData_Vimeo90K_600k_B2G8_PIL
model_type: EDVRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90KDatasetOTF
    dataroot_gt: /home/hdr/disks/D/Datasets/vimeo_septuplet/sequences
    dataroot_lq: /home/ext/gaihe/vimeo90kMETA/vimeo_septuplet_matlabLRx4/sequences
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    # val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    num_frame: 7
    lq_size: 64
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true
    use_edge: false
    OTFMode: PIL

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 200
    prefetch_mode: muti-scale
    pin_memory: true
    scale: [4]

  val:
    name: Vimeo90K-Test
    type: Vimeo90KDatasetOTFTest
    dataroot_gt: /home/ext/gaihe/vimeo90kMETA/vimeo_septuplet/sequences
    dataroot_lq: /home/ext/gaihe/vimeo90kMETA/vimeo_septuplet_matlabLRx4/sequences
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_test_GT.txt
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    io_backend:
      type: disk

    num_frame: 7
    padding: reflection_circle

    cache_data: false
    random_reverse: false
    use_flip: true
    use_rot: true
    use_edge: false
    OTFMode: PIL
    
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
    prefetch_mode: muti-scale
    pin_memory: true
    scale: [4]
    fixed_scale: 4


# network structures
network_g:
  type: EDVR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 32
  num_frame: 7
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 20
  center_frame_idx: ~
  hr_in: false
  with_predeblur: false
  with_tsa: true

# path
path:
  # pretrain_network_g: experiments/103_EDVR_L_x4_SR_REDS_woTSA_600k_B4G8_valREDS4_wandb/models/net_g_600000.pth
  strict_load_g: false
  # resume_state: /home/gaihe/gaihe/BasicSR-master/experiments/Baseline_EDVR_M_x4_SR_MSVRData_Vimeo90K_240k_B2G8/training_states/155000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [50000, 100000, 150000, 150000, 150000, 300000, 300000, 600000, 600000]
    restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  total_iter: 2400000
  warmup_iter: -1  # no warm up
  tsa_iter: 200000
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 5e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
