# general settings
name: Baseline_EDVR_M_x4_SR_MSVRData_Vimeo90K_600k_B2G8_PIL
model_type: EDVRModel
scale: 4
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 10
fix_hr: true

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: msVimeo90KDataset
    dataroot_gt: /home/hdr/disks/D/Datasets/vimeo_septuplet/sequences
    dataroot_lq: /home/hdr/disks/D/Datasets/vimeo_septuplet_matlab_X1_X4
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    io_backend:
      type: disk

    num_frame: 7
    lq_size: 64
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true
    use_edge: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 200
    prefetch_mode: cuda
    pin_memory: true
    scale: [4.0]

  val:
    name: msVid4
    type: msmtVid4
    dataroot_gt: datasets/Vid4/gt
    dataroot_lq: /home/hdr/disks/D/Datasets/vid4_matlabX1_X4
    io_backend:
      type: disk

    cache_data: false
    num_frame: 7
    padding: reflection_circle
    fixed_scale: 4.0
    scale: [4.0]


# network structures
network_g:
  type: EDVR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_frame: 7
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 40
  center_frame_idx: ~
  hr_in: false
  with_predeblur: false
  with_tsa: true

# path
path:
  # pretrain_network_g: experiments/103_EDVR_L_x4_SR_REDS_woTSA_600k_B4G8_valREDS4_wandb/models/net_g_600000.pth
  strict_load_g: false
  # resume_state: /mnt/hard_disk/gaihe/code/BasicSR-master/experiments/026_MSVR_600K_Pcd8TSAReconsMeta_Charbonnier_F7Feat64BN2/training_states/50000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [50000, 100000, 150000, 150000, 150000, 300000, 300000, 600000, 600000]
    restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  tsa_iter: 50000
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 5e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
