# general settings
name: 001_NewVABNL1Loss  # initialization

model_type: NewVA
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: areaDataset
    type: areaDataset
    brdf_args:
      nbRendering: 1
      size: 256
      order: pndrs
      toLDR: True
      lampIntensity: 1
      lightdir: [0, 0.3, 1]
    data_path: /home/sda/svBRDFs/trainBlended # Ruby
    # data_path: /home/xh/cjm/18single_image/Data_Deschaintre18/trainBlended # 2080Ti
    # rendering_path: /home/sda/svBRDFs/
    light_mode: parallel
    input_mode: render
    log: False
    gamma: False
    io_backend: 
      type: disk
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: areaDataset
    type: areaDataset
    brdf_args:
      nbRendering: 1
      size: 256
      order: pndrs
      toLDR: True
      lampIntensity: 1
      lightdir: [0, 0.3, 1]
    data_path: /home/sda/svBRDFs/testBlended # Ruby
    # data_path: /home/xh/cjm/18single_image/Data_Deschaintre18/trainBlended # 2080Ti
    # data_path: /home/xh/cjm/18single_image/Data_Deschaintre18/testBlended # 2080Ti
    # rendering_path: /home/sda/svBRDFs/
    log: False
    gamma: False
    light_mode: parallel
    input_mode: render
    io_backend: 
      type: disk
    len: 18

# network structures
network_g:
  type: NewVANetBN
  input_channel: 3
  output_channel: 3
  rough_channel: 1
  brdf_args:
    nbRendering: 1
    size: 256
    order: pndrs
    toLDR: True
    lampIntensity: 1
    # lampIntensity: 12

# network_d:
#   type: PatchDiscriminator
# path
path:
  # pretrain_network_g: ~
  strict_load_g: true
  # resume_state: experiments/001_UNETwoHF/training_states/280000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-5
    weight_decay: 0
    betas: [0.5, 0.999]
  scheduler:
    type: MultiStepRestartLR
    milestones: [600000, 600000]
    # milestones: [1,5,10,15]
  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  # highfrequency_opt:
  #   type: L1Loss
  #   loss_weight: 0.01
  #   reduction: mean
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
# validation settings
val:
  # val_freq: !!float 1e0
  val_freq: !!float 2e4
  save_img: true

  metrics:
    # cosine: # metric name, can be arbitrary
    #   type: cos
    #   weight: 2
    pixel: # metric name, can be arbitrary
      type: pix
      weight: 1
    highfrequency: # metric name, can be arbitrary
      type: HF
      weight: 1
    normal_highfrequency: # metric name, can be arbitrary
      type: nHF
      weight: 1
    diffuse_highfrequency: # metric name, can be arbitrary
      type: dHF
      weight: 1
    roughness_highfrequency: # metric name, can be arbitrary
      type: rHF
      weight: 1
    specular_highfrequency: # metric name, can be arbitrary
      type: sHF
      weight: 1
    lowfrequency: # metric name, can be arbitrary
      type: LF
      weight: 1
    SSIM:
      type: ssim
      weight: 1

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true