# general settings
name: 0001_MSAN_pointbaseline  # point, l1 loss, baseline, surfacenet

model_type: SurfaceNetModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: areaDataset
    type: areaDataset
    brdf_args:
      nbRendering: 1
      size: 256
      order: pndrs
      toLDR: True
      lampIntensity: 12
    light_args:
      type: RectLighting
      texture: [tmp/x.png, tmp/y.png]
      textureMode: Torch
    # data_path: /home/hdr/disks/D/Datasets/svBRDFs/trainBlended
    data_path: /home/sda/svBRDFs/trainBlended #Ruby
    rendering_path: /home/sda/svBRDFs/
    light_mode: point
    input_mode: render
    gamma: true
    io_backend: 
      type: disk
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: areaDataset
    type: areaDataset
    brdf_args:
      nbRendering: 1
      size: 256
      order: pndrs
      toLDR: True
      lampIntensity: 12
    light_args:
      type: RectLighting
      texture: [tmp/x.png, tmp/y.png]
      textureMode: Torch
    # data_path: /home/hdr/disks/D/Datasets/svBRDFs/testBlended
    gamma: true
    data_path: /home/sda/svBRDFs/testBlended
    rendering_path: /home/sda/svBRDFs/
    light_mode: point
    input_mode: render
    io_backend: 
      type: disk
    len: 14

# network structures
network_g:
  type: SurfaceNet
  brdf_args:
    nbRendering: 3
    size: 256
    order: pndrs
    toLDR: True
    lampIntensity: 12
  outputMapping:
    Normal: 3
    Diffuse: 3
    Roughness: 1
    Specular: 3

path:
  # pretrain_network_g: ~
  strict_load_g: true
  # resume_state: /home/sda/klkjjhjkhjhg/experiments/0012_LSDN_realtimerender/training_states/250000.state
# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 4e-5
    weight_decay: 0
    betas: [0.9, 0.999]
  optim_d:
    type: Adam
    lr: !!float 4e-5
    weight_decay: 0
    betas: [0.9, 0.999]
  scheduler:
    type: MultiStepRestartLR
    milestones: [400000, 600000]
    # milestones: [1,5,10,15]
  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  # msssim_opt:
  #   type: MSSSIMLoss
  #   window_size: 11
  #   normaliza: True
  #   loss_weight: 0.88
  # render_opt:
  #   type: L1LogLoss
  #   loss_weight: 0.2
  #   reduction: mean
  # gan_opt:
  #   type: GANLoss
  #   gan_type: vanilla
  #   real_label_val: 1.0
  #   fake_label_val: 0.0
  #   loss_weight: 0.15

# validation settings
val:
  val_freq: !!float 2e4
  save_img: true

  metrics:
    # cosine: # metric name, can be arbitrary
    #   type: cos
    #   weight: 2
    pixel: # metric name, can be arbitrary
      type: pix
      weight: 1

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true